# build go application
name: Golang CI
on: [push]
jobs:
  build:

    runs-on: windows-latest
    
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
    - run: go build
    - run: go test
      env:
      CI: true
